# frozen_string_literal: true

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = '2'

overrides = "#{__FILE__}.local"
eval File.read(overrides) if File.exist?(overrides)

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'fedora/32-cloud-base'

  config.vm.hostname = 'vagrant-premo-tinyemu.iit.jp'

  config.vm.network :private_network, ip: '172.28.128.20'

  config.vm.synced_folder 'temu/', '/temu'

  config.vm.provider 'virtualbox' do |vb|
    vb.name = 'vagrant-premo-tinyemu'
    vb.gui = false
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end

  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
end
